export const productsList = [
  {
    img: "./src/assets/option1.png",
    name: "CAMISETA MESCLA",
    price: "28,00",
    sale: "até 3x de R$9,33",
    size: "M",
    color: "Amarelo",
    createdAt: "2023-01-01",
  },
  {
    img: "./src/assets/option2.png",
    name: "SAIA EM COURO",
    price: "398,00",
    sale: "até 10x de R$39,80",
    size: "M",
    color: "Amarelo",
    createdAt: "2023-01-02",
  },
  {
    img: "./src/assets/option3.png",
    name: "CARDIGAN TIGRE",
    price: "398,00",
    sale: "até 10x de R$39,80",
    size: "G",
    color: "Amarelo",
    createdAt: "2023-01-03",
  },
  {
    img: "./src/assets/option4.png",
    name: "CARDIGAN OF WHITE",
    price: "99,90",
    sale: "até 3x de R$33,30",
    size: "GG",
    color: "Amarelo",
    createdAt: "2023-01-04",
  },
  {
    img: "./src/assets/option5.png",
    name: "BODY LEOPARDO",
    price: "129,90",
    sale: "até 3x de R$43,43",
    size: "U",
    color: "Amarelo",
    createdAt: "2023-01-05",
  },
  {
    img: "./src/assets/option6.png",
    name: "CASACO PELOS",
    price: "398,00",
    sale: "até 10x de R$39,80",
    size: "U",
    color: "Amarelo",
    createdAt: "2023-01-06",
  },
  {
    img: "./src/assets/option7.png",
    name: "CROPPED STRIPES",
    price: "120,00",
    sale: "até 3x de R$40,00",
    size: "U",
    color: "Azul",
    createdAt: "2023-01-07",
  },
  {
    img: "./src/assets/option8.png",
    name: "CARDIGAN TRANSPARENTE",
    price: "398,00",
    sale: "até 10x de R$39,80",
    size: "U",
    color: "Branco",
    createdAt: "2023-01-08",
  },
  {
    img: "./src/assets/option9.png",
    name: "CARDIGAN TIGRE",
    price: "510,00",
    sale: "até 10x de R$39,80",
    size: "U",
    color: "Rosa",
    createdAt: "2023-01-09",
  },
];
